[tasks.pi-test-run]
dependencies = ["build", "pi-test-stop"]
script_runner = "@duckscript"
script = '''
exec scp target/arm-unknown-linux-gnueabihf/debug/epd-clock pi@raspberrypi.local:/tmp/epd-clock
spawn ssh pi@raspberrypi.local "chmod +x /tmp/epd-clock && /tmp/epd-clock"
sleep 5000
'''

[tasks.pi-test-stop]
script_runner = "@duckscript"
script = '''
echo stopping all epd-clock processes
exec ssh pi@raspberrypi.local "pkill epd-clock"
'''
